#!/bin/sh

# fetch
C='\033[1;34m'
G='\033[1;33m'
B='\033[0;30m'
#C="\033[1;3$(( $RANDOM * 6 / 32767 + 1 ))m"
NC='\033[0m'

# todo
uptime="0"

echo "$B ,o()()o,  ${C}$USER$NC"
echo "$B,o'    'o,  ${C}dt${NC}  $(date '+%b. %d' | awk '{print tolower($0)}')"
echo "$B'O $G.  .$B O'  ${C}up${NC}  $uptime"
echo "$B  ·____·"
echo ""
